### ISSUE TITLE
Not working @ 07/30/2016

### ISSUE THREAD

**Issue by a4m** [YongHaoWu/NeteaseCloudMusicFlac#10]
no songs downloaded,no dir(songs_dir) made.

**Comment by YongHaoWu** [comment]
@a4m It work on my PC. How did you use this program? Mind you, your playlist must have many hot songs, some songs do not have FLAC.

**Comment by a4m** [comment]
I test the example you given (http://music.163.com/#/playlist?id=145258012)
It WORKS.
Maybe I should try to find other resources. 
issue closed.
