### ISSUE TITLE
No matches for wildcard？

### ISSUE THREAD

**Issue by TMily** [YongHaoWu/NeteaseCloudMusicFlac#12]
~/NeteaseCloudMusicFlac/python3_main.py http://music.163.com/#/playlist?id=145258012
No matches for wildcard 'http://music.163.com/#/playlist?id=145258012'.  (Tip: empty matches are allowed in 'set', 'count', 'for'.)
fish: python ~/NeteaseCloudMusicFlac/python3_main.py http://music.163.com/#/playlist?id=145258012

**Comment by YongHaoWu** [comment]
hi @TMily, when you use Python3, you should use python3 to start the script.

```python3 ~/NeteaseCloudMusicFlac/python3_main.py ```

**Comment by TMily** [comment]
我用的是ArchLinux默认的python调用的就是Python3.5.2

**Comment by YongHaoWu** [comment]
@TMily 斜杠不用， #与?与=都要转义符：P

**Comment by TMily** [comment]
我又试了下 建议更新下readme 链接可以加双引号包裹就不用转义了，另外songs_dir也需要手动建立

**Comment by YongHaoWu** [comment]
@TMily  不需要手动建立songs_dir. 谢谢建议，的确用引号包括就好了

**Comment by TMily** [comment]
@YongHaoWu 但是我用py3版本如果不建立的话会提示找不到文件 是因为权限问题？

**Comment by YongHaoWu** [comment]
@TMily 应该是，你给权限试试看？

**Comment by YongHaoWu** [comment]
@TMily 已更新ReadMe了。
