### ISSUE TITLE
README里面的示例命令有问题

### ISSUE THREAD

**Issue by 3dnc** [YongHaoWu/NeteaseCloudMusicFlac#13]
### python2示例命令

	$ python main.py 'http://music.163.com/#/playlist?id=145258012'

### python3示例命令

	$ python3 python3_main.py 'http://music.163.com/#/playlist?id=145258012'

### python2示例命令

	$ python main.py http://music.163.com/#/playlist?id=145258012

### python3示例命令

	$ python3 python3_main.py http://music.163.com/#/playlist?id=145258012

**Comment by YongHaoWu** [comment]
请问你的系统跟命令行终端是？
我是zsh，没有引号不行。 在bash上测试，有没有引号都可以。

**Comment by 3dnc** [comment]
我的是windows系统，在cmd下操作的，用引号会有问题，不带引号就可以了。
