### ISSUE TITLE
从网易下来的无损有时候会变声。。

### ISSUE THREAD

**Issue by FTAndy** [YongHaoWu/NeteaseCloudMusicFlac#20]
http://music.163.com/#/album?id=2685152

这个专辑里面的 rap 变得不能听了，很多声都消掉了

可以换个源？

**Comment by FTAndy** [comment]
http://music.163.com/#/artist?id=32665怎么感觉英文的歌全都变音了，卧槽，根本听不了

**Comment by YongHaoWu** [comment]
@FTAndy 这可能是百度的假无损。。。我回去试试

**Comment by YongHaoWu** [comment]
@FTAndy 我下载听了，感觉一切正常。
