### ISSUE TITLE
下载的时候出错了

### ISSUE THREAD

**Issue by fengkx** [YongHaoWu/NeteaseCloudMusicFlac#21]
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    size = int(headers['Content-Length']) / (1024 ** 2)
  File "/usr/local/lib/python2.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
   
python

---

Traceback (most recent call last):
  File "python3_main.py", line 64, in <module>
    size = round(int(headers['Content-Length']) / (1024 ** 2), 2)
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
    

python3

---
开始正常下了几首歌，然后出错了

**Comment by YongHaoWu** [comment]
@fengkx 好的，我看看

**Comment by YongHaoWu** [comment]
@fengkx 可否提供你的运行程序命令给我看看？ 想知道你下的是哪个歌单。
以及你的系统是 windows 吗？在 mac 下，两台电脑都正常。

**Comment by fengkx** [comment]
python3 python3_main.py 'https://music.163.com/#/playlist?id=8471571'
系统是Ubuntu 16.04 LTS 桌面版

**Comment by YongHaoWu** [comment]
@fengkx 在 mac 一切正常，估计在 ubuntu 也是一样
$ python3 python3_main.py 'https://music.163.com/#/playlist?id=8471571'
fetching msg from https://music.163.com/#/playlist?id=8471571

花洒
find songid: 7321030
find songlink:
http://yinyueshiting.baidu.com/data2/music/39380407/7321030252000745.flac?xcode=81eff6ba1e96de9bbd5cc648288db746
花洒 is downloading now ......
今日
find songid: 14590660
find songlink:
http://yinyueshiting.baidu.com/data2/music/9fc7b75a06e38af88a76899d6a9b8956/266544344/145906601509476461493.flac?xcode=154f12c74e1dbb876f333bb99c6701d9
今日苗山歌最多 is downloading now ......


火鸟
find songid: 23552480
find songlink:
	do not have flac

活着多好(Live)
简爱
find songid: 128214837
find songlink:
http://yinyueshiting.baidu.com/data2/music/128298068/128214837162000128.mp3?xcode=97584707e458b9e7350a5c038dd045b5
孤城简爱 is downloading now ......


the size of /Users/yonghaohu/mycode/NeteaseCloudMusicFlac/songs_dir/孤城简爱-冷漠.flac (3.99 Mb) is less than 10 Mb, skipping
拾回
find songid: 264699971
find songlink:
http://yinyueshiting.baidu.com/data2/music/33cca34605f373d38181c9cc4b7cb3c7/544694055/264699971126000877.flac?xcode=154f12c74e1dbb8706d3b5c82f9312a3
拾回 is downloading now ......


Moonlight Shadow
find songid: 13926864
find songlink:
	do not have flac

幸灾乐祸(Live)
岁月如歌
find songid: 483102
find songlink:
http://yinyueshiting.baidu.com/data2/music/124839842/483102194400128.mp3?xcode=1945c7a2545245e796a2d3f13bf86a03
岁月如歌 is downloading now ......


the size of /Users/yonghaohu/mycode/NeteaseCloudMusicFlac/songs_dir/岁月如歌-陈奕迅.flac (3.17 Mb) is less than 10 Mb, skipping
人来人往(Live)
歌·颂
find songid: 7354447
find songlink:
http://yinyueshiting.baidu.com/data2/music/35542606/73544471509487261959.flac?xcode=154f12c74e1dbb8738b319dd5c3c046e
歌·颂 is downloading now ......


飞花
find songid: 2092202
find songlink:
http://yinyueshiting.baidu.com/data2/music/6f3ee02ada211a728e1489dd2de19ecb/266505568/209220293600487.flac?xcode=7af5dcd957b4f75a265fb8d128cb5641
飞花歌 is downloading now ......

Allegro, Opus 3.3 a.m.
find songid: 313300
find songlink:
http://yinyueshiting.baidu.com/data2/music/125391732/313300100800944.flac?xcode=750938fde1f2fcd8b123be2e4a685e68
Allegro, Opus 3.3 A.M. is downloading now ......

床边故事
find songid: 266322535
find songlink:
http://yinyueshiting.baidu.com/data2/music/35ea8fc9df37e8667840d1fd1f8bcdff/266322566/2663225351509487261977.flac?xcode=c1697670a85b225d48ae5c20176c0886
床边故事 is downloading now ......

**Comment by YongHaoWu** [comment]
再尝试一次试试？可能是网络原因

**Comment by fengkx** [comment]
python3 python3_main.py 'https://music.163.com/#/playlist?id=8471571'
fetching msg from https://music.163.com/#/playlist?id=8471571 

花洒
find songid: 7321030
find songlink: 
http://yinyueshiting.baidu.com/data2/music/39380407/7321030252000745.flac?xcode=ad3de9b8b906aca8265fb8d128cb5641
花洒 is already downloaded. Finding next song...


今天只做一件事
find songid: 7868294
find songlink: 
http://yinyueshiting.baidu.com/data2/music/125392177/7868294223200824.flac?xcode=ad3de9b8b906aca8265fb8d128cb5641
今天只做一件事 is already downloaded. Finding next song...


非礼
find songid: 18281267
find songlink: 
http://yinyueshiting.baidu.com/data2/music/125580757/1828126715095880611034.flac?xcode=ad3de9b8b906aca80e36f2067d58dcad
非礼 is already downloaded. Finding next song...


森林
find songid: 540526283
find songlink: 
http://yinyueshiting.baidu.com/data2/music/022c12fcc8394fcc8c011c8bdce9d756/540526290/5405262831509588061837.flac?xcode=ad3de9b8b906aca80e36f2067d58dcad
森林小精灵 (好童星叶天边版） is already downloaded. Finding next song...


留低锁匙
find songid: 1066483
find songlink: 
	do not have flac

アイロニ
find songid: 73931116
find songlink: 
	do not have flac

深い森
时代を超える想い1
I am
find songid: 74165755
find songlink: 
	do not have flac

Grip!
find songid: 622974
find songlink: 
	do not have flac

遠い道の先で
Dearest
find songid: 1131693
find songlink: 
	do not have flac

ANGELUS -アンジェラス-
君がいない未来
青い栞
前前前世 (movie ver.)
大个女
find songid: 246454
find songlink: 
	do not have flac

怯
find songid: 2088346
find songlink: 
http://yinyueshiting.baidu.com/data2/music/124828174/2088346208800763.flac?xcode=ad3de9b8b906aca87ed60eb536e08c87
怯 is already downloaded. Finding next song...


Dear Leslie
find songid: 539464256
find songlink: 
	do not have flac

追
find songid: 542369506
find songlink: 
http://yinyueshiting.baidu.com/data2/music/313171c0d7597d8e479b205417766564/542369601/542369506208800128.mp3?xcode=e4bb8b01cfce6480a0d51cfc739c1004
Traceback (most recent call last):
  File "python3_main.py", line 64, in <module>
    size = round(int(headers['Content-Length']) / (1024 ** 2), 2)
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

@YongHaoWu 还是不行，这里的KeyError写'content-length'是不是因为歌曲的问题

**Comment by YongHaoWu** [comment]
@fengkx 那可能是这首歌曲的 headder 里没有提供  content-length， 我做一下处理，一会@你再试试。

**Comment by YongHaoWu** [comment]
@fengkx 已修复，请更新代码后再试试。

**Comment by fengkx** [comment]
@YongHaoWu  可以了，谢谢～

**Comment by YongHaoWu** [comment]
@fengkx You 're welcome.
