### ISSUE TITLE
提示Download finish，但目录里一首歌也没有

### ISSUE THREAD

**Issue by ohblue** [YongHaoWu/NeteaseCloudMusicFlac#22]
下载功能失效了吗？

**Comment by YongHaoWu** [comment]
@ohblue 并没有，有可能是歌单里的歌曲，没有找到无损的。可以试试其他的歌单

**Comment by bepbao** [comment]
我拿古典音乐榜试了下，这里面是有无损的，但是也没有东西。http://music.163.com/#/playlist?id=71384707
输出
`fetching msg from http://music.163.com/#/playlist?id=71384707

Tchaikovsky: Piano Concerto No.1 in B flat minor, Op.23 - 1. Allegro non troppo e molto maestoso - Allegro con spirito
find songid: 
102646166
find songlink: 
	do not have flac


================================================================

Download finish!
`

**Comment by YongHaoWu** [comment]
@bepbao 因为下无损的地方并不是在网易云音乐，而是去别的地方找的。。所以要找些流行点的，可能。

**Comment by YongHaoWu** [comment]
@bepbao @ohblue
抱歉，存在一个 问题，网易云音乐修改了些东西，以至于我在几天前只能拉到第一首歌曲。。。

所以你们下载为空。现在已经修复好了，重新下载脚本，用新的就可以了_。
