### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by sakurajiang** [YongHaoWu/NeteaseCloudMusicFlac#24]
不能通过歌曲名下载吗？我用歌曲名下不来，只能用歌单才能下。。。

**Comment by YongHaoWu** [comment]
@sakurajiang 对的，暂时不支持。你可以去看我的 感谢列表里，有人做了这个功能的

**Comment by YongHaoWu** [comment]
@sakurajiang http://imfangli.github.io/baidu-music-downloader/ 可以试试这个

**Comment by sakurajiang** [comment]
恩，我找到了，谢谢！

**Comment by sakurajiang** [comment]
@YongHaoWu 恩，我找到了，谢谢！

**Comment by sakurajiang** [comment]
@YongHaoWu 为什么使用这个网址，同一首歌在手机上无法下载，但是在电脑上能，我在那边提了问题，作者还没回我，所以想问一下你。

**Comment by YongHaoWu** [comment]
@sakurajiang  可能是判断了 agent。改一下手机浏览器 agent？
