### ISSUE TITLE
卡在运行main.py，百度如何运行.py文件但是出现错误。

### ISSUE THREAD

**Issue by ZJJane** [YongHaoWu/NeteaseCloudMusicFlac#27]
1.win10 python2.7.x
2.D:\>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    print "fetching msg from " + sys.argv[1] + "\n"
IndexError: list index out of range

**Comment by YongHaoWu** [comment]
@ZJJane 在这条命令`.D:>python main.py`里，后面要接上你想下载的那个网易云音乐歌单的地址（url）

**Comment by ZJJane** [comment]
可以了谢谢，不过还有一个问题：
怎么下载自己喜欢的音乐或者自己收藏的音乐，贴上自己喜欢的音乐地址回车就显示下载完了，但一曲都没有下

**Comment by ZJJane** [comment]
成功运行了，但是下载一两首又下不了了，一直都是is downloading now ......

**Comment by YongHaoWu** [comment]
@ZJJane 麻烦给输出信息看看？

**Comment by ZJJane** [comment]
@YongHaoWu 
![image](https://user-images.githubusercontent.com/27692584/34674527-3d4fbcd0-f4c1-11e7-9473-ff7447145ef8.png)
是这个吗？

**Comment by YongHaoWu** [comment]
@ZJJane  对的，是这个信息。

看起来都有正常下载啊。 do not have flac 是说这个歌曲没有找到无损的
is downloading 是说在下载中。

下载完，歌曲在你运行的这个脚本的 songs_dir 的文件夹里。

**Comment by ZJJane** [comment]
我发图的那个歌曲一个多小时还没下完，看了文件夹，里面只有计算前面下完的歌，那首下载中的是0b。
我估计是我电脑弄到了什么，下次换台电脑试试。
感谢你的赐教了。
