### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by RecluseWind** [YongHaoWu/NeteaseCloudMusicFlac#28]
CMD输入命令后提示：
  File "main.py", line 7
    `<`!DOCTYPE html`>`
    ^
SyntaxError: invalid syntax

**Comment by YongHaoWu** [comment]
@RecluseWind 请问输入的是什么命令？

**Comment by RecluseWind** [comment]
@YongHaoWu 
就是“python main.py 歌单地址“，无论时2.7还是3.6都一样。模块我也按照说明安装了。

**Comment by YongHaoWu** [comment]
@RecluseWind 奇怪。可以把输入的命令跟命令行的输出一并给出来？

**Comment by RecluseWind** [comment]
@YongHaoWu 
![default](https://user-images.githubusercontent.com/22146920/35381540-96ce9be4-01f7-11e8-9798-90b5445aa9f5.JPG)

**Comment by HydroCarbon13579** [comment]
我也是报这个错

**Comment by fredzhang** [comment]
我也是！

**Comment by fredzhang** [comment]
发现问题了， 如果你是从浏览器，邮件点击main.py， 下载， 那么chrome 浏览器就会下载一个网页，而不是main.py 源文件。 正确的方法clone the git repo, and run ptyon main.py from there.

**Comment by YongHaoWu** [comment]
@RecluseWind @HydroCarbon13579

fredzhang 的答案是正解。没想到是下载了网页。。
