### ISSUE TITLE
win10 python3 cmd无法使用

### ISSUE THREAD

**Issue by 1368129224** [YongHaoWu/NeteaseCloudMusicFlac#31]
执行下面命令(带单引号)：
python python3_main.py 'http://music.163.com/#/my/m/music/playlist?id=171170686'
结果是：
E:\zzc\music>python python3_main.py 'http://music.163.com/#/my/m/music/playlist?id=171170686'
fetching msg from 'http://music.163.com/#/my/m/music/playlist?id=171170686'

Traceback (most recent call last):
  File "python3_main.py", line 13, in <module>
    r = requests.get(url,headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36'})
  File "C:\softwares\python3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\softwares\python3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\softwares\python3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\softwares\python3\lib\site-packages\requests\sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\softwares\python3\lib\site-packages\requests\sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for ''http://music.163.com/my/m/music/playlist?id=171170686''

执行下面命令(不带单引号)：
python python3_main.py http://music.163.com/#/my/m/music/playlist?id=171170686
结果是：
E:\zzc\music>python python3_main.py http://music.163.com/#/my/m/music/playlist?id=171170686
fetching msg from http://music.163.com/#/my/m/music/playlist?id=171170686

================================================================

Download finish!
Songs' directory is E:\zzc\music/songs_dir
但是music目录下并没有songs_dir目录，歌曲也没有下载

**Comment by YongHaoWu** [comment]
@1368129224 你好， http://music.163.com/#/playlist?id=171170686
这个才是你真正的歌单。
注意到` http://music.163.com/#/my/m/music/playlist?id=171170686` 里带有 my/m

**Comment by 1368129224** [comment]
@YongHaoWu 
好的，能用了。
但是目前使用有几个问题:
1.识别率太低，一个歌单20首，只下载了4首。(是平台没有那些资源的无损吗？)
2.下载的歌曲只是歌名相同，歌手和歌单中的不同，所以还是无法正常使用。
谢谢你做了这个项目，对我来说非常有用。希望进一步完善。

**Comment by YongHaoWu** [comment]
@1368129224 
对的，识别率很低（其实是你的歌单里的歌比较小众），这也没办法。。
我心血来潮就会升级一下@——@

不用客气。 ：P
有人用就很开心了。
