### ISSUE TITLE
urllib.request模块已被弃用

### ISSUE THREAD

**Issue by zhangcanfeng612** [YongHaoWu/NeteaseCloudMusicFlac#39]
只需使用urllib

**Comment by YongHaoWu** [comment]
@zhangcanfeng612 Noted. Thanks. 稍候调查一下

**Comment by YongHaoWu** [comment]
@zhangcanfeng612 
你好，不太懂你说的弃用是指什么意思。

https://docs.python.org/3.0/library/urllib.request.html

python3里是有这个模块的。
