### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by guoyida** [YongHaoWu/NeteaseCloudMusicFlac#4]
It doesn't work with Python 3. Is it possible to create a python 3 compatible version?

**Comment by YongHaoWu** [comment]
@guoyida  Sure. Will solve this problem later.

**Comment by YongHaoWu** [comment]
@guoyida  Hi, Python 3 support had added.  Please check the project page and find python3_main.py.

**Comment by guoyida** [comment]
赞速度啊！

**Comment by YongHaoWu** [comment]
@guoyida 233 那我关issue啦.
