### ISSUE TITLE
No Connection adapters were found

### ISSUE THREAD

**Issue by FixYouZi** [YongHaoWu/NeteaseCloudMusicFlac#40]
![tim 20180523141124](https://user-images.githubusercontent.com/35181810/40406431-35eb76a0-5e93-11e8-8507-dc8d4d10cf21.png)
试了测试的歌单地址也是这个报错

**Comment by animagiq** [comment]
我也一样 估计是网易出手了？

**Comment by YongHaoWu** [comment]
@animagiq @FixYouZi 我试过python2.7跟 python3都没有问题，你们试试用最新的代码？
命令 `python2.7 main.py 'https://music.163.com/#/playlist?id=8471571'`

**Comment by Titanssword** [comment]
我开始也遇到这个问题，后来看报错信息，链接上有两个单引号，后来把网址的单引号去掉就可以了，改后命令python2.7 main.py https://music.163.com/#/playlist?id=8471571
