### ISSUE TITLE
文件名问题？

### ISSUE THREAD

**Issue by nmweizi** [YongHaoWu/NeteaseCloudMusicFlac#48]
windows目录不能有引号",filename再替换下。
Traceback (most recent call last):
  File "python3_main.py", line 113, in <module>
    with open(filename, "wb") as code:
OSError: [Errno 22] Invalid argument: 'D:\\python\\NeteaseCloudMusicFlac/songs_dir/Light And Lovely-Arnett Cobb,Arthur Edgehill,Buddy Tate,Coleman Hawkins,Eddie "Lockjaw" Davis,George Duvivier,Shirley Scott.flac'

**Comment by YongHaoWu** [comment]
@nmweizi Noted, 稍候就转换 引号 到其他符号

**Comment by nmweizi** [comment]
还有单引号

**Comment by nmweizi** [comment]
https://www.polarxiong.com/archives/Python-%E6%9B%BF%E6%8D%A2%E6%88%96%E5%8E%BB%E9%99%A4%E4%B8%8D%E8%83%BD%E7%94%A8%E4%BA%8E%E6%96%87%E4%BB%B6%E5%90%8D%E7%9A%84%E5%AD%97%E7%AC%A6.html
def validateTitle(title):
    rstr = r"[\/\\\:\*\?\"\<\>\|]"  # '/ \ : * ? " < > |'
    new_title = re.sub(rstr, "_", title)  # 替换为下划线
    return new_title

**Comment by YongHaoWu** [comment]
@nmweizi 收到，现在试试改改。

**Comment by YongHaoWu** [comment]
@nmweizi 感谢反馈。改好了，之前重构了 Python2的，现在 python3的也重构一下。

**Comment by YongHaoWu** [comment]
@nmweizi 已提交。请验收0_0
