### ISSUE TITLE
字符集处理

### ISSUE THREAD

**Issue by nmweizi** [YongHaoWu/NeteaseCloudMusicFlac#50]
--- Logging error ---
Traceback (most recent call last):
  File "d:\python36\lib\logging\__init__.py", line 995, in emit
    stream.write(msg)
UnicodeEncodeError: 'gbk' codec can't encode character '\xf6' in position 86: illegal multibyte sequence
Call stack:
  File "python3_main.py", line 123, in <module>
    logger.info("%s is downloading now ......\n\n" % songname)
Message: 'Kickstart My Heart (as made famous by Mötley Crüe) is downloading now ......\n\n'
Arguments: ()

**Comment by YongHaoWu** [comment]
@nmweizi 可以顺便提供一下你的歌单吗？

**Comment by nmweizi** [comment]
一不小心，给没了

**Comment by YongHaoWu** [comment]
@nmweizi  现在最新的版本应该是修复了这个问题了~你可以试试看。
