### ISSUE TITLE
有声读物不能下载

### ISSUE THREAD

**Issue by nmweizi** [YongHaoWu/NeteaseCloudMusicFlac#51]
https://music.163.com/#/djradio?id=527382612&order=1&_hash=programlist&limit=100&offset=100
能否增加功能
谢谢

**Comment by Rabbit233** [comment]
同求有声读物的下载
顺便问一下数字专辑也是可以下载的吗？

**Comment by YongHaoWu** [comment]
@nmweizi  @Rabbit233  有声读物恐怕比较难找到 flac -_-  

还是自己去搜索下载比较快~
