### ISSUE TITLE
下载320k 的音乐可以给个版本吗？谢谢

### ISSUE THREAD

**Issue by AaronLiang** [YongHaoWu/NeteaseCloudMusicFlac#55]
下载320k 的音乐可以给个版本吗？谢谢

**Comment by YongHaoWu** [comment]
@AaronLiang 你好，已经加上了配置参数了。你重新用最新的代码，看说明文档就好 了

**Comment by YongHaoWu** [comment]
下载所有歌曲, 包括 MP3 在内
$ python3 main.py 'http://music.163.com/#/playlist?id=145258012' mp3
