### ISSUE TITLE
  File "main.py", line 8     print "fetching msg from " + sys.argv[1] + "\n"                              ^ SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by lvhailong** [YongHaoWu/NeteaseCloudMusicFlac#6]
File "main.py", line 8
    print "fetching msg from " + sys.argv[1] + "\n"
                             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by YongHaoWu** [comment]
@lvhailong Hi, please note that you should use python2.x when you use the script main.py.
In this case, you should use python3_main.py because you used python3. Right?

**Comment by lvhailong** [comment]
yes, because my python2 cannot install pip or requests model properly.

**Comment by YongHaoWu** [comment]
@lvhailong Is the issue solved now ?
