### ISSUE TITLE
下载的歌曲与歌单不匹配（匹配率低）

### ISSUE THREAD

**Issue by Iridescentangle** [YongHaoWu/NeteaseCloudMusicFlac#62]
测试的一个歌单链接如下
https://music.163.com/playlist?id=2564966520
歌单中有一首DOROTHY的Raise Hell和一首m.o.v.e的Rage Your Dream，但是下载后的文件夹里只有一首Raise Hell，而且不是这一首,是Raise Hell (1983 Demo)-Thor.flac
是不是我什么地方打开方式不对啊...

**Comment by zhouhua666** [comment]
测试了我的歌单，里边一共5首歌，没有一首是对的。。。是不是准确率太低了啊

**Comment by YongHaoWu** [comment]
@zhouhua666 是低。。你可以试试100首的歌单的-_-

**Comment by caldeer** [comment]
算是一个可以的了   50首下30来首   待我完全学完我也来做一个   到时候请多指教

**Comment by Shabo-Master** [comment]
97首，对了三首。加油加油！

**Comment by willyoungforever** [comment]
哎，希望能有点正确率吧。。加油啦！！！

**Comment by wolfcon** [comment]
我的龟龟...这太低了...

[https://music.163.com/playlist?id=805044609](https://music.163.com/playlist?id=805044609) 这个歌单感觉全军覆没了

**Comment by guodong2005** [comment]
感谢作者，让我发现了一个全新的歌单
