### ISSUE TITLE
显示下载成功，创建了song-dir文件夹但没有歌曲（人在国内）

### ISSUE THREAD

**Issue by CoolHermione** [YongHaoWu/NeteaseCloudMusicFlac#65]
[Song.txt](https://github.com/YongHaoWu/NeteaseCloudMusicFlac/files/2729068/Song.txt)
试了几个歌单，都显示下载成功，但是路径文件夹里没有歌曲，不知道是什么问题呢？
文件里的歌单链接是https://music.163.com/#/artist?id=29333

**Comment by YongHaoWu** [comment]
@CoolHermione 你会看到 log 里面有很多 "[WARNING]       do not have flac" 的字样，意味着只能找到 mp3  - - 

你要是 mp3也可以接受，在运行的命令最后，加上 mp3 即可。github 项目说明有说到

**Comment by CoolHermione** [comment]
也试了加mp3，还是木有下载出来0.0 不知道肿么回事

**Comment by YongHaoWu** [comment]
@CoolHermione  你把你运行的命令粘贴一下，还有运行后的 log~

**Comment by CoolHermione** [comment]
[songs.txt](https://github.com/YongHaoWu/NeteaseCloudMusicFlac/files/2729386/songs.txt)
^_^烦请赐教

**Comment by YongHaoWu** [comment]
@CoolHermione 客气

`python C:\Users\Moretz\Desktop\NeteaseCloudMusicFlac-master\main
.py https://music.163.com/#/artist?id=29333`

这是 你运行的命令对吧？


你要在后面接上 mp3，应该是这样子：

`python C:\Users\Moretz\Desktop\NeteaseCloudMusicFlac-master\main
.py https://music.163.com/#/artist?id=29333 mp3 `

**Comment by CoolHermione** [comment]
后面加上mp3也下载不出来0.0

**Comment by YongHaoWu** [comment]
@CoolHermione  log 发一下

**Comment by CoolHermione** [comment]
[mp3.txt](https://github.com/YongHaoWu/NeteaseCloudMusicFlac/files/2729483/mp3.txt)
log在此~

**Comment by YongHaoWu** [comment]
@CoolHermione 理论上 ` C:\Users\Moretz/songs_dir`这个文件夹应该是有的，你看看?

**Comment by CoolHermione** [comment]
哈哈 我觉得也是呢 理论上应该有。。我再研究一下

**Comment by YongHaoWu** [comment]
@CoolHermione 情况如何？不行试试最新版的代码。

**Comment by CoolHermione** [comment]
好哒，感谢，我再试试新版～

**Comment by YongHaoWu** [comment]
@CoolHermione 可以用吗~

**Comment by CoolHermione** [comment]
可以啦！感谢！
