### ISSUE TITLE
mac下neteaseMusic怎么播放flac格式的歌曲啊

### ISSUE THREAD

**Issue by xingstarx** [YongHaoWu/NeteaseCloudMusicFlac#9]
参考了作者的项目，下载下来的歌曲，在mac下可以用neteaseMusic播放吗

**Comment by YongHaoWu** [comment]
@xingstarx 你添加本地音乐，找到下载了的无损音乐，就可以了。

**Comment by YongHaoWu** [comment]
@xin

**Comment by YongHaoWu** [comment]
@xingstarx 抱歉，好像neteaseMusic无法播放本地无损。

**Comment by xingstarx** [comment]
恩，多谢了。能推荐下mac播放无损的播放器吗

**Comment by YongHaoWu** [comment]
@xingstarx Amarra处理的很好，但是有点笨重。VOX就灵活些。

**Comment by xingstarx** [comment]
恩，多谢啦。。
